version: '3'

services:
  foltia:
    build: .
    environment:
      TZ: Asia/Tokyo
      MIRAKURUN: mirakurun:40772
      DLNAROOT: /home/foltia/php/tv/DNLAroot # ./tv/DNLAroot
      ENABLE_PHPPGADMIN: 0
      ENABLE_SHELLINABOX: 0
      ENABLE_MINIDLNA: 0
      ENABLE_SAMBA: 0
    ports:
      - 80:80
      #- 139:139       # samba
      #- 445:445       # samba
      #- 138:138       # samba
      #- 8200:8200     # minidlna
      #- 1900:1900/udp # minidlna
    hostname: foltia
    volumes:
      - ./data/db:/var/opt/rh/rh-postgresql95/lib/pgsql/data
      - ./data/at:/var/spool/at
      - ./data/cron:/var/spool/cron
      - ./tv:/home/foltia/php/tv
      - ./neroAacEnc/linux/neroAacEnc:/home/foltia/perl/tool/neroAacEnc
    restart: always

